# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:4.8
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Save pkg version to a file
          command: node ./.circleci/scripts/read-changelog.js > .pkg-version

      - run:
          name: Save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha

      - save_cache:
          key: v1-build-{{ checksum ".circle-sha" }}
          paths:
            - ~/repo

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-build-{{ checksum ".circle-sha" }}
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl

      - run:
          name: Build, push and deploy Docker image
          command: |
            echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcp-key.json"

            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
              export PKG_VER="$(cat .pkg-version)"

              # config file
              echo ${KEYSTONE_CONFIG} | base64 -i --decode > config.js

              # gcs key file
              echo ${GCS_KEY_FILE} | base64 -i --decode > gcskeyfile.json

              docker build -t gcr.io/coastal-run-106202/keystone-plate:$PKG_VER .
              gcloud docker -- push gcr.io/coastal-run-106202/keystone-plate:$PKG_VER
              kubectl set image deployment/keystone-plate keystone-plate=gcr.io/coastal-run-106202/keystone-plate:$PKG_VER
              kubectl rollout status deployment/keystone-plate
            fi


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - release
